### ISSUE TITLE
Note delay (request from facebook)

### ISSUE THREAD

**Issue by JoepVanlier** [JoepVanlier/Hackey-Trackey#13]
Would it be possible to add a note delay column or would that be really hard in this context? (Would make lowering resolution less destructive too)

**Comment by JoepVanlier** [comment]
I think this should in principle be possible.

The information for note delay is never destroyed. Notes that were entered via the normal midi editor are not quantized. I wanted to avoid widening the pattern view too much, so maybe a shortcut to manually enable this for a specific column would be good. Then as a second rule, if notes are significantly shifted from zero for at least one note in a column, make sure the note delay is displayed. The only thing I have to be careful about is shortening the note when a note delay is applied. Otherwise it may overlap with the next one and cause a recolumning. This feature will probably take a bit of iterating to get non-buggy. What resolution would be good? 0-128 to keep the numbering the sample as with the other columns? A single column would probably not be accurate enough, right?

I don't think it will change anything to the destructiveness of changing the resolution though. In principle a resolution change will do nothing except shuffle the notes to different channels. If two notes are on the same row in a channel, it's not like they get removed, they just get moved to a different column.

**Comment by r4dian** [comment]
Most trackers in Buzz use 0x00-FF.
So does IT (pxx vol command).

Renoise gets around the width by having +/- buttons to reveal& hide columns within a track, maybe the same is possible ?

**Comment by JoepVanlier** [comment]
Added in commit 65a2424521c47d469eb7b9e5d598f29456e8ec7e . Note though that for it to work reliably, the ppq per row needs to be set to a multiple of 256.
