### ISSUE TITLE
Can only pan left (bug report from facebook)

### ISSUE THREAD

**Issue by JoepVanlier** [JoepVanlier/Hackey-Trackey#14]
Tracker seems to only be able to pan left.

**Comment by JoepVanlier** [comment]
Suspect this is a signed vs unsigned parameter issue. I assumed all parameters would go from 0 to 1. Maybe some go from -1 to 1. I will look into this.

**Comment by r4dian** [comment]
Pan, Width & their pre-fx equivalents seem to be signed.
Buzz would have 0x80 as centre in almost all machines.

**Comment by JoepVanlier** [comment]
Fixed in 8fd7ff15323ee67f648106006ed681f464f8beb7 . 

However, as far as I am aware, whether the parameter is two-sided cannot be polled from the envelope (couldn't find it in the envelope chunk anyway), therefore there is a hard-coded list of symmetric envelopes for now.
