### ISSUE TITLE
CC column request (from facebook)

### ISSUE THREAD

**Issue by JoepVanlier** [JoepVanlier/Hackey-Trackey#15]
CC column is useful, but can only display one at a time. Perhaps it should show one for each CC that has data (with a shortcut to add another for) or just whichever are selected in reapers normal editor.

**Comment by JoepVanlier** [comment]
I've thought about having a column per CC command type as well.

Problem is, how would you add a CC column the first time? I've considered adding a column with a command number, and having that trigger the creation of a new column, but I figured that automating things with actual automation envelopes is much more common. Especially when there's ReaControlMIDI to map envelopes to CC.

Anyways! I could add a feature to add a column of interest.

**Comment by r4dian** [comment]
I was thinking about external hardware, but ReaControlMIDI covers that case I think.

**Comment by r4dian** [comment]
Maybe ctrl-plus when in a cc column adds another (would need a way to specify which) ctrl-minus hides current cc column again? 

I'm not really sure what a logical UX for this would be.

**Comment by JoepVanlier** [comment]
Added in commit 7277fbcad66188171de674cde614af16ffaa7498 .

Ctrl \+ \+ brings up 'more' stuff. For the CC events, go to the mod section, enter the types of CC events you want on different lines, then hit CTRL + + to split them into separate columns. Note that emptying a column will mean it disappears again (for now). I will probably make them persistent until the tracker is reset or the columns are refolded in a future version.

CTRL \+ \- will collapse it again. Note that overlapping events will not be deleted, but overwriting one will delete all the events on that row when in collapsed mode.

**Comment by JoepVanlier** [comment]
Modified in commit 7cbc62b5793a09caa6504e2c5dcf4801544fd6da .

Multi-column mode is activated when expanding the mod column (expand by going to the CC column
and pressing CTRL \+ \+). In this mode, every CC command type gets its own channel. You can 
remove a column with CTRL \+ Shift \+ \-, which will delete all the CC data in that 
column as well as remove the column. You can add a new column with CTRL \+ Shift \+ \+
after which you have to enter a numeric value and hit RETURN.

Hint: If you want this to be the default mode, then edit the script and change 
tracker.modMode to 1.
