### ISSUE TITLE
Tab column switching (from facebook)

### ISSUE THREAD

**Issue by JoepVanlier** [JoepVanlier/Hackey-Trackey#16]
Please add tab to next note column (& shift-tab to previous note column.)

**Comment by r4dian** [comment]
> This I will do next time I code on the project. I assume just making it go to the next column 'class' is fine?

This is probably the same behaviour, I'd have to check the script to see what you mean. In Buzz' pattern editor, tab jumps from global params to the first track's first parameter (which is note by convention except in Unwieldy Tracker machine & a few others), then to the 1st parameter of the next track, etc.

**Comment by JoepVanlier** [comment]
Added in commit 22a11d517f176a5eadbc17eb3bc3fa2cbd037984 :)
