### ISSUE TITLE
If the Hacky-Tracky window is docked, it un-docks when the help is opened

### ISSUE THREAD

**Issue by r4dian** [JoepVanlier/Hackey-Trackey#19]
1. Open the tracker
1. Dock the window (right click on titlebar to reveal option)
1. Ensure the tracker has focus
1. Press F1

##### Results
Actual: Window undocks and the help appears
Expected: Window remains docked and the help appears

**Comment by JoepVanlier** [comment]
Thanks for the report! Fixed in commit 2e39562fe47a6da07858834a9aeb64c7e015d903 :)
