### ISSUE TITLE
First column is CC but with "...." underneath it

### ISSUE THREAD

**Issue by magwa101** [JoepVanlier/Hackey-Trackey#21]
I'm not sure if I should put what may be just a user error into an issue but I thought it may help. 

Subject says it all, this image also shows the issue:
![image](https://user-images.githubusercontent.com/873819/36880020-2f3dd462-1d8c-11e8-9d9b-d90f63f369ab.png)

A separate question is that I tried out Volume automation and FF did not place it at the top most value.

PS I really like this tracker idea. I downloaded renoise to see if it could be a tool for me, I'm not so sure, but something like what you're doing as an add on rather than a whole program seems perfect.

**Comment by JoepVanlier** [comment]
I'm not sure what you mean by the first error. Did you enter a CC event there and it does not show up? Typically you would only see CC events (i.e. changes in the CC state) in that column.

The second issue (FF not being full volume) I will look into when I get home. Are you referring to the volume of the track? And what do you consider full volume? 0 dB?

**Comment by JoepVanlier** [comment]
Yeah, it seems FF maps to 0 dB for the volume. This was by design actually. Personally, I rarely mix with positive ceilings. Would you prefer if the ceiling was configurable? FF being +6.ish dB then?

**Comment by magwa101** [comment]
Imma close this and do more reading on this tool. I'll get deeper before more questions.
