### ISSUE TITLE
Mouse cursor placing operation as in Buzz. (Enhancement)

### ISSUE THREAD

**Issue by r4dian** [JoepVanlier/Hackey-Trackey#22]
Buzz lets you both:

- Click to place the cursor
- Click-drag to highlight a block for copy/paste

Two people on Facebook suggested adding this,
Mouse position is available in the Reaper API

**Comment by JoepVanlier** [comment]
Added! :)

**Comment by r4dian** [comment]
Doesn't seem to work except that mousewheel moves cursor; do I need to change a value somewhere to enable it ?

**Comment by JoepVanlier** [comment]
That's strange. No, there's no flag to change. 

It works here: https://imgur.com/a/E4t0V

Did you pull?

**Comment by JoepVanlier** [comment]
It was added in b01d1d5256a53cfb1944a64f8731366bb4eab82a

**Comment by r4dian** [comment]
Aha sorry: it only works when the scrollbar is present.
I was trying a single bar MIDI item.

**Comment by JoepVanlier** [comment]
Yes, apologies. You're absolutely right. I accidentally put it in with the scrollbar condition.

Fixed in 2cf4cb3ebc93d7a3300d2bbe2b52193f0ca173a9 :)

**Comment by r4dian** [comment]
That's nailed it. :)

**Comment by JoepVanlier** [comment]
@michaelsjackson Could you please refrain from commenting on closed issues? This issue was opened for a specific thing which was fixed. If there is a feature missing, open a new issue.

**Comment by michaelsjackson** [comment]
Sorry, I was using this more like a forum, I guess. Ok, will start a new feature request.
