### ISSUE TITLE
idea: program change, in advanced col options

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Trackey#34]
Having additional program change column in advanced col options would give you immediate access to the entire current sound bank, and you could switch sounds per line. This is especially cool if you use Out[C] option where each column triggers on a different midi channel. I hope you like this idea as well.

**Comment by JoepVanlier** [comment]
I've started work on this. It may still be a bit rough around the edges. In the options screen, enable "Enable CC's for all channels (beta)" (this setting is remembered).

After this:
Ctrl + Shift + A adds a CC column to all channels. Note that after you hit this key, you have to enter the number for the one you want (e.g. 32).
Ctrl + SHIFT + - gets rid of a column.

It's not rigorously tested yet, so if you run into issues, let me know. Also note that channel 1 in the tracker, is really MIDI channel 2 (for implementational reasons).

**Comment by JoepVanlier** [comment]
Added in a821c69021351cf7b8e22853c140a50670e786da . Please open a new issue if it doesn't work as intended.
