### ISSUE TITLE
Allowing ENTER to trigger hackey patterns

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Trackey#37]
So we can use in both directions ENTER, as in buzz.

**Comment by michaelsjackson** [comment]
But somehow I like ENTER for pattern playback as well, hmm. Alt-ENTER for playback and ENTER for editing maybe.

**Comment by JoepVanlier** [comment]
Custom keyboard layouts can be made.

**Comment by michaelsjackson** [comment]
But what is the command to trigger hackey patterns?
