### ISSUE TITLE
Getting strange error when starting hackey-trackey

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Trackey#38]
bad argument to format, number expected got nil

Not sure what is causing this. Maybe a restart of computer will help, as in Windows XP days. :)

This error appeared today first time, after I played around with automation items, in other projects. Closed Reaper, restarted, reinstalled hackey-trackey and this error always appears now, strange thing.
![hackey_trackey_format_error](https://user-images.githubusercontent.com/5049512/46697121-37a87800-cc14-11e8-8812-e2d85331dffc.png)

**Comment by michaelsjackson** [comment]
Yay, found the causing error. I wanted to test unchecking 'Use settings stored in pattern', mainly for playing around with trim/read of automation values, for finding other interesting values, AFTER I wrote a pattern in hackey trackey, somehow hackey trackey does not like it, so for now I have to keep this always checked.

How were you using this option? Or for what was it meant for?

**Comment by JoepVanlier** [comment]
Thanks! That anrrowed it down quite a lot. It should be fixed in: 8c356b6740121a8b946ec9b6fff7d8a35b64ecb6

That option toggles whether your preferences for Octave, Envelope, Advance and CC column format are stored on a per MIDI item basis (checked), or globally (unchecked).
