### ISSUE TITLE
Hitting F9 started a window flickering light show, making window and Reaper unusable

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Trackey#39]
What helped then was, `ctrl-alt-f1, pkill reaper`

Then in config, after setting `scaleActive = 0
`brought back normal behaviour again. So never use F9 again. :)

**Comment by JoepVanlier** [comment]
Can you record this behaviour for me? I'm very curious what it looks like and why it may be happening on your end. F9 normally opens the scale helper, which can be pretty useful for coming up with chord progressions quickly.

**Comment by JoepVanlier** [comment]
I suspect that this may have to do with the minimum size enforcement somehow. But it's difficult to find out what is going on exactly. It is possible that it may have been remedied in the latest update, since I changed the handling of the size enforcement a little bit.

**Comment by michaelsjackson** [comment]
Now the problem has gone, thanks for guessing and finding a solution.

**Comment by JoepVanlier** [comment]
Cool.
