### ISSUE TITLE
Trim read, previously entered values? Changing all trimmed values in pattern.

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Trackey#40]
Not sure if this would be possible.

I edit some pattern in hackey-trackey, changing various fx settings to my taste. So far so good.

Later in Reaper's arrange I use trim/read on the previously entered automation values, to fine tune it to a better result. Now it would be cool, if hackey trackey would be able to update all its previous values to the newly trimmed results. Or is this already possible? I guess this is not possible now, in v1.78.

**Comment by michaelsjackson** [comment]
It keeps all relative values, but adds or subtracts a constant value from all values.

if your value is x it does `x  +/-  diff
`, then setting diff back to zero, so the trim knob stay always in the middle, and you can go up or down, you will never reach the end of the slider, you can trim as often as you want, until you like the result. This is at least how I understood trim so far.

Now if I change the automation slider in 'trim/read' mode, I can hear the changes, but after opening the pattern again using hackey-trackey, it returns back to what I had before 'trimming', thus my trim/read slider modifications are lost.

**Comment by JoepVanlier** [comment]
I don't do anything in particular that should reset trimming. My guess would be that it affects the maximum and minimum value of an envelope (see also your issue on FF). This type of operation is currently unsupported. Shift + +/- can up and down regulate an entire column of values.

**Comment by michaelsjackson** [comment]
Just checked, shift  +/- works on selections, even better. Wonderful, then I will use that method. There are too many too useful commands, so some are lost in the forest, like this one.

Without any selection shift  +/-  only changes the current value.

**Comment by JoepVanlier** [comment]
Alright, assuming this solved. :)
