### ISSUE TITLE
Saving user keysets in .cfg, so our changes are not lost after next update

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Trackey#41]
Or can we do this already? I wrote my changes in the forum, but somehow this keyset does not exist in the program yet. Most flexible would be if there would be a text file which I can edit, and this would be loaded as last, overwriting any previous definitions, so I can be sure my definitions are used.

I am using mainly defaul keyset, plus those F9..F12 from renoise keyset, moving the original ones to ctrl-F9..F12. Plus a few more modifications I had. But before going further with this, I should be sure my changes are not lost after next update.

**Comment by JoepVanlier** [comment]
This is now implemented in update ab1abfa1ae4fbadbbe6f3e231f5fed0c344005fa .

After you start the tracker next time, it will generate a mapping userkeys.lua in the tracker folder. You can edit this at will, it will never be overwritten and all the keymaps you add there will appear in the menu.

Note though, that what you write here has to be valid lua, or it will not work :)
