### ISSUE TITLE
Duplicate (ctrl-d) could switch immediately/automatically to the duplicated pattern

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Trackey#44]
Most times if I duplicate a pattern, I want to move and edit there as well. So this step could happen automatically.

**Comment by JoepVanlier** [comment]
This is already the default behavior.

**Comment by michaelsjackson** [comment]
Here duplicate duplicates the item, selects the new item copy, but the old loop range stays in tact, so I need to hit once ctrl-right, so it jumps to next/new copied item.

In short I need to press: ctrl-d, ctrl-right
instead of only: ctrl-d

Not a big issue. How does it behave there, does the looping range move with the item? Maybe it depends what exact setting one has for time selection, loop points...

**Comment by JoepVanlier** [comment]
What do you mean, the old loop range stays intact?
Do you have follow song on? That might be pushing you back.

**Comment by michaelsjackson** [comment]
I tried also with follong song off, still same. I am guessing it is related to loop range not being linked to time selection.

**Comment by JoepVanlier** [comment]
Well, duplication doesn't affect the loop range, but you should still see the new pattern and edit the new pattern when you type in notes.

**Comment by michaelsjackson** [comment]
I see, so I can edit, but without hearing the results of my edits, I see. Ok, for the cases, where you can imagine the end result this would work, otherwise, usually one needs to listen to the result.
