### ISSUE TITLE
Now having custom keysets, can we define for any hotkey binding, any reaper action?

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Trackey#47]
That would bring entire Reaper action/custom action world into hackey trackey itself.

It could be implemented as a 5. column in keyset definitions, beside CTRL, ALT, SHIFT, Keycode would be additionally 'Action' where you would write the action id. Wow, such a simple and powerful design that would be. All midi editor actions could be used in hackey trackey. In hackey patterns all arrange actions could be used.

**Comment by michaelsjackson** [comment]
This would be something like adding a rocket under hackey trackey, converting it instatly to an outer space tracker, with millions of extra features, thanks to all action developers, plus those which will be developed in future. Glad you liked the idea, plus it seems to be possible. Wonderful.

**Comment by JoepVanlier** [comment]
Surprise! Added it today in 38d8e8b509bb8892b5497b5db51d461884c24a4a .

The syntax is as follows:
`keys.startPat       = { 0,    0,  0,    13,  "Hackey Sequencer/Sequencer/HackeyPatterns_exec.lua" }`

That last field can either contain a path (relative to the script directory) or a command ID such as `"_RS484e8164422fa1077f696f9825c0e0f71d5bbaae"` (note the `"`'s).

**Comment by michaelsjackson** [comment]
What happens if you redefine an available hotkey mapping from above, it is overwritten, right?

Example:
    keys.enter          = { 0,    0,  0,    13 }            -- Enter        

later:
    keys.startPat       = { 0,    0,  0,    13,  "Hackey Sequencer/Sequencer/HackeyPatterns_exec.lua" }

What will run, if I press Enter? keys.enter or keys.startPat or both? I am guessing both because both have different names (keys.enter vs. keys.startPat), correct?

What would you suggest as best use case form?
- Should we map multiple commands to same binding or better not?

Having a few suggestions how to use this feature right or in most powerful way, would be great.

**Comment by michaelsjackson** [comment]
One use case tip, its own window should be closed first, using a custom action, then doing the next triggering.

Example for `Enter`:
```
tracker: close tracker, start patterns
patterns: close patterns, start tracker
```

**Comment by JoepVanlier** [comment]
That Enter command is special in that it is used for determining when you hit enter after renaming a pattern or such. I would really suggest not changing that one.

For all the others, a core key (one without that last argument) always takes precedence and results in no custom commands being called for that key anymore. For the remainder you can bind multiple commands to one key, but they will be executed in a random order.

**Comment by michaelsjackson** [comment]
`For the remainder you can bind multiple commands to one key, but they will be executed in a random order.`

Wow, this sounds almost like a feature. Bringing the necessary randomness to editing, if you wish so. Just map some crazy algorithms to same key and get surprised what will be applied. Cool.

**Comment by JoepVanlier** [comment]
They will all be called though ;).
