### ISSUE TITLE
keys.shpatdown      = { 1,    0,  0,    26161 }         -- CTRL + F1   seems not to work correctly

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Trackey#50]
This seems not to do the opposite of ctrl-f2
(from renoise key bindings)

**Comment by JoepVanlier** [comment]
In what sense? Here it seems to do so.

**Comment by michaelsjackson** [comment]
Now, it seems to work, great. In some previous version it did something else, maybe the cause was something on my side, not sure. Great that it works now, can be closed.
