### ISSUE TITLE
right mouse click, defines a block from current cell to clicked cell

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Trackey#51]
Defining a block between current cell position and right clicked mouse button. Imagine the emacs behaviour with the mouse, from point (current cell here) to right click, selecting a range. Same principle here. Simple, direct, powerful.

**Comment by JoepVanlier** [comment]
Instead of RMB twice, 2.57 introduces a combo where you click left and then right somewhere to select a region.

Basically first click left, then right to select a region. I hope that works for you.

**Comment by JoepVanlier** [comment]
Closed as implemented feature.
