### ISSUE TITLE
Duplicate cell or line/row value 4 lines below, with wrapping would not hurt

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Trackey#52]
You have sound/line you like, want to copy it a few more times in same phase position within the bar, this command would help.

There could be two variants:
a)  duplicates only cell
b)  duplicates entire row/line     <--  this would be very practical, together with automation values

The main idea here is duplication happens to 4 lines further position. Same as copy row, go 4 lines further, paste row.

**Comment by JoepVanlier** [comment]
CTRL + B, CTRL+B, CTRL+C will copy the current line. Then pg down and then CTRL + V to paste should be pretty quick, no?

**Comment by JoepVanlier** [comment]
Closing this as `wontfix`, since it's already possible with existing functionality.
