### ISSUE TITLE
Too bad in wine we can not dock lua script windows like trackey or patterns

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Trackey#54]
Then we could save screensets where on the left is the normal midi editor, on the right
(a)  hackey trackey
(b)  hackey patterns

With enter you would jump between trackey <> patterns on the right, the left side staying same, for example.

**Comment by michaelsjackson** [comment]
This is a Reaper issue.

**Comment by JoepVanlier** [comment]
Reaper issue.
