### ISSUE TITLE
Cursor following hackey patterns, inside hackey trackey, like in arrange

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Trackey#55]
Scrolling in hackey patterns does not move the cursor inside hackey trackey (but it does in arrange), following inside hackey trackey could be also useful for longer patterns. Then no matter how long the pattern is, you can easily find the right place, via hackey patterns, and do your quick edits, inside hackey trackey. Best of both worlds.
- better big picture navigation (hackey patterns) over tracks, bars, beats
- direct editing (hackey trackey)

**Comment by JoepVanlier** [comment]
There is an option for followsong already in Hackey Trackey, which makes
sure that the current time cursor stays in visible range. Since HP moves
this cursor, this should also follow it when it is moved in HP.

I'm not going to add explicit send messages for this between HP and HT
because I want them to be independent and I don't want HT polling for such
custom data all the time.

**Comment by michaelsjackson** [comment]
Yes, all good arguments. Do not remember but because of something I disabled this follow song option. I think for normal editing, you mentioned it is better disabling it, then you can play elsewhere and edit in a different point. No problem, if the pattern is too big, we can simply split it, edit, then rejoin, all in one custom action, did not test it, but if we can use custom actions anyway, we could also build workaround solutions.

**Comment by JoepVanlier** [comment]
I could probably make something that detects where you doubleclick the
pattern and passes this to HT. Would that solve the problem for you?

**Comment by JoepVanlier** [comment]
Oh wait, I misunderstood the request the first time I read it. Sure, this can be added as an option.

**Comment by JoepVanlier** [comment]
Added in 091e3ff8fab50901c095ab08b755180cc20c48df
