### ISSUE TITLE
Tracker in a Notator GUI (any image background), possible?

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Trackey#56]
Would it be possible to use any image background for the tracker? On the left, in arrange you could see hackey patterns, and there you go, both views in one. Ready to rok. :) 

Both programs could be still developed separately, this new 4. program (after tracker, machines, patterns) would do basically following:
- take an image or svg background
- load tracker to some pixel position with given size
- load patterns to some pixel position with given size
Something like docker in reaper, if it would work in wine, but here the additional coolnes would be take any image/feeling and combine with what we have already in one interface. I should ask this in reaper forum, as well. 

![atari_tracker](https://user-images.githubusercontent.com/5049512/47952669-364c4000-df73-11e8-83a5-f640a613bc16.png)

**Comment by JoepVanlier** [comment]
No sorry, this sounds like a nightmare to maintain and would cause a lot of disk thrashing (from loading the images all the time), which is really not nice.

It would be nice to have a feature like a script docker for reaper, where the docker is some floating window that can support multiple windows, but I don't really want another project, so I'm not going to be writing one, sorry :D

**Comment by michaelsjackson** [comment]
For the fun of it I might try this at some point using AutoHotkey, there is Dock. 
https://github.com/camerb/AHKs/blob/master/thirdParty/Dock.ahk

The good point, you could have as many background images as you like, e.g. taking some hardware image, and in the edit window HT would sit. Like some Elektron device, for example. Would be more fun to look at at least, also for YouTube surprise effect.
