### ISSUE TITLE
attempt to perform arithmetic on a nil value (field '?')

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Trackey#57]
..m Files\REAPER\Scripts\Tracker tools\Tracker\tracker.lua:2764: attempt to perform arithmetic on a nil value (field '?')

**Comment by JoepVanlier** [comment]
I need more than that to figure out what's going on there. What were you
doing at the time, do you have a project file that can reproduce it, etc.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
