### ISSUE TITLE
Step-record from incoming midi notes rather than qwerty input

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Trackey#58]
It would be cool, if we could step record also from midi input, not only qwerty input. This can be useful if you have some midi playback devices you like, it would offer you alternative methods of playing in in step-record mode. So the interface is only different, but the method would be just the same, still step-record using the hackey trackey Advance settings.

Ctrl-R it should step record, also from midi input, hit Esc, only playback, as is with qwerty. Esc again and you can record. Directly inside hackey trackey, never leaving it, be it via qwerty (what is already possible) or midi (not available yet, I guess).

**Comment by JoepVanlier** [comment]
It's not a bad idea, if it were easy, but this is something that cannot easily be done within the Lua API. Receiving MIDI messages is something that's in the JSFX domain. From Lua, I cannot catch incoming MIDI messages. While with the latest extensions to REAPER it is technically possible to communicate between JSFX and Lua, I don't want to start yet another plugin.

**Comment by dusanmsk** [comment]
... but you have made it and you are fuckin insane !!!
Thank you !!!!

**Comment by michaelsjackson** [comment]
Yes, now we have it already. Thanks Joep!
I like how you can record from midi in real-time, using normal record in Reaper, then hackey track is disabled, showing RECORDING or so, but also normal step recording. I like especially the replace mode with Alt-T, showing as N inside hackey trackey.
