### ISSUE TITLE
no ability to change row highlighting?

### ISSUE THREAD

**Issue by petervanhaaften** [JoepVanlier/Hackey-Trackey#59]
I am looking to change which row is highlighted. For instance, how do I set Hackey Trackey to highlight every 7th row instead of every fourth? I have looked all through the options and help pages and not seen this function documented, but maybe it exists already. Thanks!

**Comment by JoepVanlier** [comment]
You are correct, there was no ability to do so until just now (commit 757ac8ba61f0421229b3ff309e4c1d0b734624fe ). In the latest version, when you change the resolution to 6, every sixth row will be highlighted. You can also override row highlighting by hitting CTRL + SHIFT + and then clicking where you want the first row highlight in the row indicator column. You can reset this override with ctrl + shift + right mouse button. I hope this helps. :)

**Comment by JoepVanlier** [comment]
No prob. I just added an option to store and retrieve it on a per pattern basis in bc606586ca248a48d62318dc0776e222c9abf80f :)

Frequent switching of time signatures sounds interesting! :D

**Comment by JoepVanlier** [comment]
No prob! Happy to help. And ghehe, thanks!

Closing this issue for now, feel free to reopen it or open a new one if it doesn't work for you.
