### ISSUE TITLE
Horizontal insert/delete and wrap

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Trackey#64]
Now we have already vertical insert/delete and its wrapped variants. What about same method but horizontally? So you could quickly shift notes to the side, making space in its original line, without deleting it. This would simplify the manual note spreading to channels.

Go to next line, shift horizontally x 1
Go to next line, shift hoirzontally x 2
Go to next line, shift horizontally x 3

**Comment by JoepVanlier** [comment]
Added in `Shift + Ins` and `Shift + Bksp` for shifting horizontally (without wrap) in 2.56.

No plans for supporting wrapping, since I'm running out of keys.
