### ISSUE TITLE
idea: Shuffle

### ISSUE THREAD

**Issue by dusanmsk** [JoepVanlier/Hackey-Trackey#66]
Could it be possible to add shuffle/swing option to tracker?

I don't know tracker internals and how you handle the notes internally, but in my (abandoned/prototype) implementation of tracker I did it:

when reading notes from midi clip:
- unswing/quantize midi clip (to make sure all notes are on quantized places so should be easily placed to pattern editor)
- read notes into local arrays (where pattern editor read/write all data until saved to midi clip)
- undo previous quantization

when writing to midi clip:
- write notes from pattern editor (without any swing, directly on the grid)
- quantize to swing grid (don't remember if it was sws or reaper action)

It was not the best way how to do it but it works.

see https://github.com/dusanmsk/reaper/blob/master/reascript/patternEditor/patternEditor.lua
lines 650 and 716, maybe shold be useful.

Or you should do manual calculation of 2nd note start position directly in the pattern editor, but dunno how to deal with situation when user change swing strength in reaper midi clip editor and shuffle notes outside hackeytrackey.

thx

thx

**Comment by dusanmsk** [comment]
BTW I see that you started 13 jan 2018 lol, my first commit was from 11 jan 2018. Shame that we didn't joined forces at the beginning (but I abandoned that very soon after prototype because have had no time for that)

**Comment by JoepVanlier** [comment]
I'll think about it, but from the top of my head the suggested implementation is incompatible with both the legato system and note delay system; which both require sub-row information, which would be wiped out in the quantization step.

**Comment by dusanmsk** [comment]
Hmm, then I could try to use some js plugin for realtime swing. Thx.

**Comment by dusanmsk** [comment]
Found "piz midi swing" plugin at https://code.google.com/archive/p/pizmidi/downloads. Works great. So problem solved.
