### ISSUE TITLE
Error when deleting midi item while tracker is open

### ISSUE THREAD

**Issue by Lexomir** [JoepVanlier/Hackey-Trackey#67]
I would expect the window to return to the "No Item is selected" screen.

This fix would probably be useful for people who only use one tracking window that switches to whatever is selected.

![image](https://user-images.githubusercontent.com/4417948/62087038-43f6d380-b22e-11e9-872b-6212dbac2a3e.png)

**Comment by JoepVanlier** [comment]
Thanks for the bug report! I forgot to check whether the track number was still valid in the handling of the recording status of the track. I have pushed a fix in 2.02. Please let me know if this resolves the issue or if you run into this issue in another condition.

**Comment by Lexomir** [comment]
Cool it works now, thanks.

**Comment by JoepVanlier** [comment]
Cool, then I'll close this. If you have any more issues, please let me know! :)
