### ISSUE TITLE
Keeping size not working when using 32 steps per bar

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Trackey#69]
The quite newly added function of keeping position and size, size is always set to 16 step length, even if I make the window bigger to 32 steps per bar, before clicking on the X on my windows top right corner. This could be a bug, I guess.

I prefer 32 steps per bar as 16 steps are not big enough for more fluid automation, at least this is the case in buzz.

**Comment by JoepVanlier** [comment]
Is this still happening on the latest version? It should save the last size.

**Comment by JoepVanlier** [comment]
Assuming this has been resolved. Please feel free to open a new ticket if needed.
