### ISSUE TITLE
Play single line (as Enter do in Renoise)

### ISSUE THREAD

**Issue by dusanmsk** [JoepVanlier/Hackey-Trackey#71]
Hello,

could it be possible to add feature that pressing some (for example "Enter") key will play all notes on selected row? Or better - switch tracker to "audible" mode so arrow keys up/down will also play selected/all columns on current row? It is meant as some stepper "scrub" mode.

Tried it myself but failed to understand all the hackeytrackey code in depth. Maybe some defer method that will do play-wait-stop should be ok for this.

Thx

**Comment by JoepVanlier** [comment]
I've added this under shift+space. :)

**Comment by dusanmsk** [comment]
But this is not exactly the same. When I press SHIFT+SPACE, song start playback from cursos position. When I press space again, playback is stopped but cursor is moved to last played position.

I meant not to use reaper command to start playback, but instead to send midi notes on selected pattern line to virtual midi output whenever that line is changed by pressing cursor up/down.

Something like:
- on up/down arrow
  - is "scrub" mode enabled
    - if yes
      - is note on current line?
         - yes -> send it to reaper
         - no -> send note off to reaper

It should be very useful during making fast riffs, you only need to enable this function temporary and navigate up/down in pattern and you instantly hear (in speed you are pressing arrows) what's exactly there.

I don't remember which tracker has this function but I am pretty sure I used it a lot 25 years ago.

**Comment by JoepVanlier** [comment]
Hey, sorry for the belated response.

How does this work for you?
https://raw.githubusercontent.com/JoepVanlier/Hackey-Trackey/scrub/Tracker/tracker.lua

Enable the toggle "recording acts as scrub mode". This will set up the virtual keyboard such that you hear the lines as you pass over them.

**Comment by JoepVanlier** [comment]
Merged it as part of 2.82 https://github.com/JoepVanlier/Hackey-Trackey/commit/508ff25188091aeb1ae9d64d81cb7ff5de26e27c
