### ISSUE TITLE
Fixed Indicator Position

### ISSUE THREAD

**Issue by craigjoy** [JoepVanlier/Hackey-Trackey#78]
Hello,

Some years ago I used to use OctaMED on the Amiga...

![OctaMED](https://i.ytimg.com/vi/ysw8m0v93xw/maxresdefault.jpg)

As you can see the edit/play indicator was fixed in the middle of the screen (as were I think most trackers back then), so I've been hacking around with Hackey Trackey to see if I can make it behave in a similar way. Not sure it's quite ready to PR, or indeed if it's a feature you'd consider including, but I thought you might be interested to take a look. 

[Here is my branch](https://github.com/craigjoy/Hackey-Trackey/tree/feature/fixedIndicator).

The new mode is enabled by selecting "Fix indicator position in view" in the options. It's intended to be used in conjunction with "Bigger play indicator" and "Follow song" enabled. Also the fixed location can be changed by holding down CTRL+ALT+LMB in the row indicator column.

Do let me know what you think, any feedback or suggestions would be much appreciated.

Many thanks, Craig.

**Comment by JoepVanlier** [comment]
Awesome! :D

I haven't been able to look at the commits in great detail yet, but I'd love a PR for this.

I can help with testing for regressions. I'll try and have a look on the weekend.

What do you prefer, that I look at your branch first and see if I can spot any obvious defects, or that we work on it on a PR? Either works for me.

Also, my apologies for exposing you to well, something that is not my finest code. There are quite some questionable decisions in the script. Lots of this was coded late at night in a half sleepy state :D

**Comment by craigjoy** [comment]
Great, glad you like the idea!

No need to apologise for your code, HT speaks for itself. This is my first dabble with lua so total novice here. Also I hacked this together under remarkably similar circumstances!

But yes, that would be great if you could go through it, I could very easily have missed regression issues. I'm happy to PR it as it is though if that makes things easier for you.

Cheers,

**Comment by JoepVanlier** [comment]
I'm gonna mark this one as resolved! 👍 

Thanks for the contrib :)

**Comment by craigjoy** [comment]
Thrilled to have contributed, it's been a sincere pleasure! I'll take a look at that glitchy positioning behaviour soon.

Many thanks, Craig.
