### ISSUE TITLE
Quickly insert note-off commands on multiple columns simultaneously

### ISSUE THREAD

**Issue by niraimegumi** [JoepVanlier/Hackey-Trackey#85]
Can you implement a shortcut to quickly insert note-off commands on all columns at the cursor/current row? Shift + the note off key doesn't work, and selecting and copy/pasting rows of note-off commands doesn't fly.

**Comment by JoepVanlier** [comment]
I just added it. Try `CTRL + -` :)

**Comment by HammyHavoc** [comment]
Beautiful!

**Comment by niraimegumi** [comment]
Thank you!
