### ISSUE TITLE
README -> Special keys: inconsistency?

### ISSUE THREAD

**Issue by BrokenGravityMusic** [JoepVanlier/Hackey-Trackey#89]
(Thanks for making the tracker. I've been looking for this this for years! Dont know why i've never found this before.)

Most places we have ASCII arrows (/\ and \\/):
<html><body>

CTRL + /\ | Shift current octave up
-- | --
CTRL + \\/  | Shift current octave down
SHIFT + CTRL + /\ | Switch envelope mode (FX automation)
SHIFT + CTRL + \\/ | Switch envelope mode (FX automation)

</body>
</html>

but "resolution" has the words "Up" and "Down". 
<html><body>

CTRL + ALT + Up | Increase row resolution
-- | --
CTRL + ALT + Down | Decrease row resolution

</body>
</html>

This makes it a bit confusing, espcially because i cannot get arrows to work, since CTRL + ALT + Arrow-key, seem to be assigned to rotating the screen by default on Windows (havent looked into changing that yet), which makes me wonder if something else is meant by "Up" & "Down" (i tried page-up/-down but it didnt work). 

Either a clarificattion on the meaning of up/down or changing them to /\ \\/ for consistency, would make this more clear.

**Comment by JoepVanlier** [comment]
Thank you for the kind words and thanks for letting me know about the docs issue! You are absolutely correct in that the shortcut listed is incorrect, sorry about that.

It should have been SHIFT + ALT + /\ and SHIFT + ALT + \/. I have just corrected this. I think it was changed in the past for exactly the reason you suggest (the default windows screen rotation shortcut).

Note that you can look up the key sets in the plugin itself as well (F1). I have also added this to the docs as a hint.

**Comment by JoepVanlier** [comment]
I'm assuming this is resolved. Please feel free to open a new issue if it isn't.
