### ISSUE TITLE
Simple request: rename midi channels to their actual numbers

### ISSUE THREAD

**Issue by offten** [JoepVanlier/Hackey-Trackey#90]
Very simple request as it's just hard to remember that midi channel 1 = midi channel 2. Just have the track names reflect this. (Unless the note transcribe function somehow needs channel 1 to show up in the GUI?

**Comment by JoepVanlier** [comment]
Fair point. They're really just labels. I've added in `2.97` it as a config option (with starting at 2 as the default).

**Comment by JoepVanlier** [comment]
Closed for inactivity :)
